stages:
  - build
  - test
  - deploy

build_image:
  stage: build
  script:
    - echo build

test:
  stage: test
  script:
    - echo "test"

deploy:
  stage: deploy
  script:
    - echo "deploying"

    # - docker build -t gitlab-spark .
    # - docker run gitlab-spark /tests/run_tests.sh
